"""Generates and stores a password or passwords given a set of parameters.

Using a series of CLI arguments and flags, this script will generate a
password or series of passwords seperate by new lines for user by the
user. The arguments allow which characters the password will use, and
how long each password will be. This module also uses the cryptography
library to encrypt password storage using a key generated by Fernet.

Typical Usage example:

    python __main__.py 10 5 -nsu
    python __main__.py 15 -sc

"""

import random
import sys
import string
import argparse
import pyperclip
import os

from cryptography.fernet import Fernet


def arg_check(
    var: string, arg1: string, arg1_desc: string, arg2: string, arg2_desc: string
) -> string:
    while var not in (arg1, arg2):
        var = (
            input(
                f"Sorry, but that wasn't a valid input. Please enter"
                f"a [{arg1.upper()}] for {arg1_desc} or [{arg2.upper()}] "
                f"for {arg2_desc}: ",
            )
            .lower()
            .strip()
        )

    return var


def pass_gen(args: object, regex: string = None) -> list:
    password: str = ""
    pass_list: list = []
    char_list: list = [string.ascii_lowercase]

    # Flags to check for password character types.
    if args.upper:
        char_list.append(string.ascii_uppercase)
    if args.number:
        char_list.append(string.digits)
    if args.special:
        char_list.append(string.punctuation)

    if regex != None:
        # Number of password to generate.
        for _ in range(args.pass_num):
            # Password generator dependent on expression.
            for x in regex:
                match x:
                    case "l":
                        password += random.choice(string.ascii_lowercase)
                    case "u":
                        password += random.choice(string.ascii_uppercase)
                    case "n":
                        password += random.choice(string.digits)
                    case "s":
                        password += random.choice(string.punctuation)

            pass_list.append(password)
            password = ""
    else:
        # Number of password to generate.
        for _ in range(args.pass_num):
            # Password generator dependent on char_num and arg flags.
            for _ in range(int(args.char_num)):
                password += random.choice(random.choice(char_list))

            pass_list.append(password)
            password = ""

    # Copy passwords if flag entered.
    if args.copy:
        pyperclip.copy("\n".join(pass_list))

    # Formatted password printing
    print("--------------------------------------------------")
    print("\n".join(pass_list))
    print("--------------------------------------------------")

    return pass_list


def store_pass(args: object, pass_list: list) -> None:
    # Check if passwords.txt already exists in current directory.
    if os.path.isfile("passwords.txt") == True:
        # If it does, ask whether to overwrite or append passwords.
        print("There is already a passwords file in the current directory.")
        write_type = input(
            "Would you like to overwrite the file or append to "
            "this file? [W] or [A]: "
        )
        write_type = arg_check(write_type, "w", "overwrite", "a", "append")
        # Ask user to confirm overwrite as long as force option wasn't used.
        if write_type == "w" and args.force == False:
            overwrite_confirm = (
                input(
                    "This will overwrite your existing"
                    " password file, are you sure? [Y] or [N]: "
                )
                .lower()
                .strip()
            )
            overwrite_confirm = arg_check(overwrite_confirm, "y", "yes", "n", "no")

        # Checks if force flag used or if user has confirmed overwrite.
        if write_type == "a" or args.force == True or overwrite_confirm == "y":
            with open("passwords.txt", write_type) as f:
                # Add extra line to list if appending
                if write_type == "a":
                    f.write("\n")
                f.write("\n".join(pass_list))
        else:
            # Rerun save function if confirmation is denied
            store_pass(args, pass_list)
    else:
        # If passwords.text doesn't exist, automatically create file.
        with open("passwords.txt", "w") as f:
            f.write("\n".join(pass_list))
        print(
            "Your passwords have been saved in the 'passwords.txt'",
            "file in the current directory",
        )


def encrypt_pass(args: object, pass_list: list) -> None:
    # Check whether there is already an active key present
    if os.path.isfile("key.txt") == True:
        with open("key.txt", "r") as f:
            key = f.read()

    else:
        # Generate a key and save it if none available
        key = Fernet.generate_key()
        with open("key.txt", "wb") as f:
            f.write(key)

        print(
            "A new key has been created in the current directory as 'key.txt'."
            " Keep this safe!"
        )
    # Create fernet object from key from cryptography library
    fernet = Fernet(key)
    # Take passwords from current file, this means that if there is
    # already a password list, it can encrypt pre-existing files
    with open("passwords.txt", "r+") as f:
        data = f.read()
    # Encrypt password list into a byte object for encryption
    with open("passwords.txt", "wb") as f:
        token = fernet.encrypt(data.encode("utf-8"))
        f.write(token)


def retrieve_pass() -> None:
    if os.path.isfile("passwords.txt"):
        # Checks if encryption has been used
        if os.path.isfile("key.txt"):
            with open("key.txt", "r") as f:
                key = f.read()

            with open("passwords.txt", "r") as f:
                token = f.read()

            # Generates fernet object form existing key and
            # decrypts passwords file
            fernet = Fernet(key)
            pass_list = fernet.decrypt(token).decode("utf-8").split("\n")
        else:
            # Otherwise if no key.txt file exists, read passwords as per normal
            with open("passwords.txt", "r") as f:
                data = f.read()
                pass_list = data.split("\n")

        # Formatted password display
        print("Passwords in passwords.txt:")
        print("--------------------------------------------------")
        for password in pass_list:
            print(password)
        print("--------------------------------------------------")

    else:
        print("There is no password.txt file in the current directory.")


def expression_gen() -> string:
    invalid_chars: list = []

    print(
        "You've selected to create an expression to use for password generation.\n"
        "A password expression is created by using a sequence of characters in a\n"
        "designated order. The characters to use are below:\n\n - [L] lowercase letter\n"
        " - [U] uppercase letter\n - [N] digit\n - [S] special character\n\n"
        "Please refer to the help guide for expression examples.\n"
    )
    expression = (
        input("Please input a compatible expression: ").lower().replace(" ", "")
    )

    while True:
        # Checks for if any characters in expression are invalid.
        for x in expression:
            if x not in ("l", "u", "n", "s"):
                invalid_chars.append(x)
        # Breaks out of check if no invalid characters
        if len(invalid_chars) == 0:
            break
        # Lets user know which characters are invalid
        print(
            "\nYour expression is not valid. The invalid characters are:\n\n - "
            f"{"\n - ".join(invalid_chars)}\n"
        )
        invalid_chars = []
        expression = (
            input("Please try to input another expression: ").lower().replace(" ", "")
        )

    return expression


def main(args):
    # If view mode, ignore generator
    if args.view:
        retrieve_pass(args)
    else:
        # Check if expression generation used first to pass expression
        if args.expression:
            expression = expression_gen()
            print("\nPasswords Generated:")
            pass_list = pass_gen(args, expression)
        else:
            print("Passwords Generated:")
            pass_list = pass_gen(args)

        # Prompts user to check if they want to save.
        save_confirm = (
            input("Would you like to save your generated passwords? [Y] or [N]: ")
            .lower()
            .strip()
        )
        save_confirm = arg_check(save_confirm, "y", "yes", "n", "no")

        if save_confirm == "y":
            store_pass(args, pass_list)
            # Checks for encryption if user has prompted to save
            encrypt_confirm = (
                input("Would you like to encrypt your saved passwords? [Y] or [N]: ")
                .lower()
                .strip()
            )
            encrypt_confirm = arg_check(encrypt_confirm, "y", "yes", "n", "no")

            if encrypt_confirm == "y":
                encrypt_pass(args, pass_list)


if __name__ == "__main__":
    # Instantiate argparse
    parser = argparse.ArgumentParser(
        description="Generates a password or series of passwords given a "
        "set of parameters"
    )

    # List of positional arguments
    parser.add_argument(
        "char_num",
        metavar="Num_of_Chars",
        nargs="?",
        default=10,
        type=int,
        help="Optionally enter a number of characters in password. (default: 10)",
    )
    parser.add_argument(
        "pass_num",
        metavar="Num_of_Passwords",
        nargs="?",
        default=1,
        type=int,
        help="Optionally create a number of passwords. (default: 1)",
    )

    # List of options
    parser.add_argument(
        "-c",
        "--copy",
        help="Copies the password to the clipboard once generated",
        action="store_true",
    )
    parser.add_argument(
        "-e",
        "--expression",
        help="Lets the generator know that you want to create an"
        " expression to control the password generation",
        action="store_true",
    )
    parser.add_argument(
        "-f",
        "--force",
        help="Forces overwrite so app ignores overwrite confirmation",
        action="store_true",
    )
    parser.add_argument(
        "-n",
        "--number",
        help="Adds numbers to password generation",
        action="store_true",
    )
    parser.add_argument(
        "-s",
        "--special",
        help="Adds special characters to password generation",
        action="store_true",
    )
    parser.add_argument(
        "-u",
        "--upper",
        help="Adds uppercase letters to password generation",
        action="store_true",
    )
    parser.add_argument(
        "--view",
        help="Instead of generating passwords, prints out passwords to terminal",
        action="store_true",
    )

    # Parse the passed arguments
    args = parser.parse_args()

    main(args)